var localization = {
    "CLOUDCONTROLCENTER": "Cloud Control Center for SAP Business One",
    "CONTROLCENTER": "æŽ§åˆ¶ä¸­å¿ƒ",
	
	"RESOURCEPOOL": "åŸºç¡€è®¾ç½®ç®¡ç�†",
	"APPMGR" : "åº”ç”¨ç¨‹åº�ç®¡ç�†",
    "SOFTWAREREPO": "Software Repository",
    "HOSTUNITS": "Service Units",
    "HOSTUNIT": "Service Unit",
    "TENANTS": "Tenants",
    "TENANT": "Tenant",
    "CUSTOMER": "Customer",
    "USERMGR": "User Management",
    "COMPANYDB": "Company Database",
    "USER": "User",
    "SOFTWARE": "Software",
    "USEDBYHU": "Used by Service Unit",
    "EXTENSIONS": "Extensions",
    "EXTENSION": "Extension",

    // Overview
    "OVERVIEW" : "Home",
    "OVERVIEW_HOSTUNIT": "Service Units",
    "OVERVIEW_SYS_LANDSCAPE": "System Landscape",
    "OVERVIEW_SOFTWARE": "Resource Pool",
    "OVERVIEW_TENANT": "Tenants",
    "OVERVIEW_REPOSITORY": "Software Repositories",
    "OVERVIEW_COLUMN_HUNAME": "Service Unit",
    "OVERVIEW_COLUMN_B1I": "Integration Component",
    "OVERVIEW_REPOSITORY_USAGE": "Repository Usage",
    "OVERVIEW_INFOPANEL": "About",
   
    "MSSQL_USEDBY_COMMONDB": "You have not unregister the sql instance, because there are many SBO-COMMON on it.",

    "TEST_CONNECTION_TIMEOUT": "Timeout",

    //////////////Application Management//////////////
    "APPMGR_OVERVIEW": "Overview",
    "APPMGR_HOSTING_UNIT": "Service Unit",
    "APPMGR_TENANT": "Tenant",
    "APPMGR_CUSTOMER":"Customer",

    //////////////Infrastructure Management//////////////
    "INFMGR_ABOUT": "Overview",

    //////////////Resource Pool//////////////
    "RES_OVERVIEW": "Overview",
    "RES_MS_SQLS" : "Database Instance",
    "RES_MS_SQL" : "Database Instance",
    "RES_LIC_SERVERS" : "License Servers",
    "RES_LIC_SERVER": "License Server",
    "RES_PRESENTATION_SERVERS": "Presentation Servers",
    "RES_PRESENTATION_SERVER": "Presentation Server",
    "RES_SBO_COMMONS": "Common Databases",
    "RES_SBO_COMMON": "Common Database",
    "RES_B1I_SERVERS": "Integration Components",
    "RES_B1I_SERVER": "Integration Component",
    "RES_SHARED_FOLDERS": "Shared Folders",
    "RES_SHARED_FOLDER": "Storage",
    "RES_SHARED_FOLDER_OPTION": "Shared Folder",
    "RES_MAILER_SERVICES": "Mailers",
    "RES_MAILER_SERVICE": "Mailer",
    "RES_MAILER_SERVICE2": "Mailer service",
    "RES_MAIL_SERVER": "Mail Server",
    "RES_B1_FOLDER": "Business One Shared Folder",
    "RES_DB_FOLDER": "Backup Repository",
    "RES_B1_FOLDER_REG": "Business One Shared Folder Registration",
    "RES_DB_FOLDER_REG": "Backup Repository Registration",
    "RES_DATABASE_TYPE" : "Database Type",
    "RES_DATABASE_USRNAME": "Database User Name",
    
    "RES_VIEWLIC_LICFILE"	:	"License File",
    "RES_VIEWLIC_SUBTITLE"	:	"The license file contains the following license types.",
    
    "RES_LIC_INSTALLATION_NUM" : "Installation Number",
    "RES_LIC_LICENSE_FILES" : "License Files",
    "RES_SBO_COMMONS_SQL" : "Corresponding Database Instance",
    
    "RES_SHARED_TYPE_B1" : "SAP Business One Shared Folder",
    "RES_SHARED_TYPE_DBBACK" : "Backup Repository",
    "RES_MISC_SELECTED_DETAIL_TITLE" : "Selected Software Component Details",
    "RES_USED_BY_TENANT": "Used by Tenants",
    "RES_USED_BY_HU": "Used by Service Units",
    
    "HU_TENANT_NUM" : "Number of Tenants",
    "HU_SW_COMPONENTS" : "Software Components",
        
    "RES_SELECTED": "Selected",
    "RES_DETAILS": "Details",

    "RES_TENANT_NUM": "Number of Tenants",
    "RES_HU_NUM": "Number of Service Units",
    "RES_MISC_NOSELECTED_TIP": "Select the {0} you want to unregister then choose the Unregister button.",
    "RES_MISC_UNREGIST_CONFIRM": "Do you want to unregister the {0}?",
    "RES_MISC_UNREGIST_CONFIRM_USED": "The selected presentation server belongs to a service unit. Do you want to unregister the {0}?",
    "RES_MISC_DELETE_CONFIRM":"Do you want to delete the {0}?",
    "RES_MISC_LOGOUT_CONFIRM": "Confirm logout?",
    //grid column
    "COLUMN_PATH"			: "Path",
    "COLUMN_DESC"			: "Description",
    "COLUMN_MSSQL_NAME"		: "Name",
    "COLUMN_DB_TYPE"		: "Database Type",
    "COLUMN_HOSTNAME"		: "Server Name",
    "COLUMN_VERSION"		: "Version",
    "COLUMN_NAME"			: "Name",
    "COLUMN_PURPOSE"		: "Purpose",
    "COLUMN_CUSTOMER_NO"	: "Number of Tenants",
    "COLUMN_PORT_NO"		: "Port",
    "COLUMN_SITE_USER"		: "Site Username",
    "COLUMN_SITE_PASSWORD"	: "Site Password",
    "COLUMN_HW_KEY"			: "Hardware Key",
    "COLUMN_USTATUS"		: "Usage Status",
    "COLUMN_INSTALL_NO"		: "Installation Number",
    "COLUMN_SYS_NO"			: "System Number",
    "COLUMN_CUSTNUM"		: "Number of Tenants",
    "COLUMN_LICSVR"			: "License Server Status",
    "COLUMN_DMUSER"			: "System User",
    "COLUMN_B1USERNAME"		: "User Code",
    "COLUMN_USERTYPE"		: "User Type",
    "COLUMN_ISSUPERUSER"	: "Super User",
    "COLUMN_STATUS"			: "User Status",
    "COLUMN_B1USERTYPELIC"	: "Business One License Modules",
    "COLUMN_USED"			: "Used",
    "COLUMN_AVAILABLE": "Available",
    "COLUMN_RELATED_DB": "Related Database Instance",
    "COLUMN_SERVER_PATH": "Server URL",
    "COLUMN_TENANT_NAME": "Customer Name",
    "COLUMN_CREATE_DATE": "Creation Date",
    "COLUMN_PROVIDER": "Provider",

    // MISC
    "MISC_CONFIGURATION" 	: "Configuration",
    "MISC_REGISTER"			: "Register",
    "MISC_UNREGISTER"		: "Unregister",
    "MISC_CREATE"			: "Create",
    "MISC_ADMINISTRATION"	: "Administration",
    "MISC_MODE" 			: "Mode",
    "MISC_SSTATUS"			: "Service Status",
    "MISC_MSTATUS"			: "Monitoring Status",
    "MISC_STATUS"			: "Status",
    "MISC_DATA_PROCESSING" 	: "Processing Data...",
    "MISC_TEST_CONNECTION" 	: "Test Connection",
    "MISC_SITEUSER"			: "B1SiteUser",
    "MISC_PROGRESS&FINISH"	: "Progress/Finish",
    "MISC_NAME"				: "Name",
    "MISC_HOSTNAME"			: "Server",
    "MISC_VERSION"			: "Version",
    "MISC_TYPE"				: "Type",
    "MISC_MODE"				: "Mode",
    "MISC_DESCRIPTION"		: "Description",
    "MISC_PORT"				: "Port",
    "MISC_SITEUSERNAME"		: "Site Username",
    "MISC_SITEUSERPSW"		: "Site Password",
    "MISC_ADD"				: "Add",
    "MISC_PROFILE"			: "Profile",
    "MISC_BASICSETTINGS"	: "Basic Settings",
    "MISC_MSSQL"			: "Database Instance",
    "MISC_CPYNAME"			: "Company Name",
    "MISC_DBTYPE"			: "Database Type",
    "MISC_LOCATION"			: "Localization",
    "MISC_COA"				: "Chart of Accounts",
    "MISC_YEAR"				: "Year",
    "MISC_QUARTER"			: "Quarters",
    "MISC_MONTH"			: "Months",
    "MISC_DAY"				: "Days",
    "MISC_CLOSE"			: "Close",
    "MISC_FINISH"			: "Finish",
    "MISC_DONE"				: "Done",
    "MISC_CUSTNAME"			: "Customer Name",
    "MISC_CONTACT"			: "Contact Information",
    "MISC_PATH"				: "Path",
    "MISC_NEW"				: "New",
	"MISC_REGISTER"			: "Register",
    "MISC_REMOVE"			: "Remove",
    "MISC_TASK_PROCESSING"  : "Processing",
    "MISC_TASK_PENDING"     : "Pending",
    "MISC_OK": "OK",
    "MISC_CANCEL": "Cancel",
    "MISC_CONFIRM": "Confirm",
    "MISC_REQUIRED": "Required",    
    "MISC_ENABLED": "Enabled",
    "MISC_DISABLED": "Disabled",

    // Login
    "LOGIN_COPYRIGHT": "Â© 2012 SAP AG. All rights reserved.",
    "LOGIN_LOGIN_FAIL": "User name or password is incorrect",
    "LOGIN_SERVER_ERROR": "Server Error",
    "LOGIN_NO_PERMISSTION": "No permission",

    "LOGOUT": "logout",

    //Tenant Management
    "B1_SUPERUSER": "Super User",
    "B1_NORMALUSER": "Normal User",

    //Software Repository
    "SW_DETAIL_TITLE": "Software Repository Details",

    // USER MANAGER
    "USR_SUPERUSER": "Cloud Operator",
    "USR_NORMALUSER": "SAP Business One User Code",
    "USED_BY_OTHER_TENANT": "The user has been used by other tenant.",
    "USER_DOES_NOT_EXIST_IN_DOMAIN": "The user does not exist in the domain.",
    
    /*************************************************Wizard*****************************************************/
    /** License Server Registration **/
    "WIZARD_LICSVR_REG"			:	"License Server Registration",
    "WIZARD_LICSVR_WEL_TITLE"	:	"Welcome to the License Server Registration.",
    "WIZARD_LICSVR_WEL_CONTENT" :	"You can use this wizard to register an SAP Business One License Server. Choose Next to continue.",
    "WIZARD_LICSVR_CONF"		:	"Configure the license server.",
    "WIZARD_LICSVR_CREATE"		:	"Creating License Server.",

    /** Service Unit Creation **/
    "WIZARD_HU_CRT"				:	"Service Unit Creation Wizard",
    "WIZARD_HU_WEL_TITLE"		:	"Welcome to the Service Unit Creation Wizard.",
    "WIZARD_HU_WEL_CONTENT"		:	"You can use this wizard to create a new Service Unit. Choose Next to continue.",
    "WIZARD_HU_GUIDE_TITLE": "Prerequisites",
    "WIZARD_HU_GUIDE_DESCRIPTION": "Before you create a new Service Unit, make sure that all the following components are ready:",
    "WIZARD_HU_BASICSETTINGS"	:	"Basic Settings",
    "WIZARD_HU_SWRESOURCE"		:	"Infrastructure Components",
    "WIZARD_HU_PSERVER"         : "Presentation Servers",
    "WIZARD_HU_REVIEW"			:	"Review",
    "WIZARD_HU_REVIEWSUBTITLE"	:	"To create the service unit, choose Next.",
    "WIZARD_HU_SWINFO"			:	"Infrastructure Components",
    "WIZARD_HU_SWSUBTITLE"		:	"Select the infrastructure components you want to add.",
    "WIZARD_HU_PRESENTATION"    : "Presentation Server",
    "WIZARD_HU_PRESENTATIONSUBTITLE": "Select one or more presentation servers.",
    "WIZARD_HU_INPUTHUINFO"		:	"Specify the basic settings for this service unit.",
    "WIZARD_HU_HUNAME"			:	"Service Unit Name",
    "WIZARD_HU_LIVSVR"			:	"License Server",
    "WIZARD_HU_MSSQL"			:	"Database Instance",
    "WIZARD_HU_SBOCOMMON"		:	"Common Database",
    "WIZARD_HU_B1I"				:	"Integration Component",
    "WIZARD_HU_DBBAKREPO"		:	"Backup Repository",
    "WIZARD_HU_MAILERSVC"		:	"Mailer Service",
    "WIZARD_HU_SBOCOMMONCRT"	:	"Create a new SBO-COMMON",
    "WIZARD_HU_HUSETTINGS"		:	"Service Unit Settings",
    "WIZARD_HU_TESTDBCONNECTION":	"Test Database Connection",
    "WIZARD_HU_TESTLICSVR"		:	"Test License Server Connection",
    "WIZARD_HU_CRTSBOCOMMON"	:	"Creating Common Database",
    "WIZARD_HU_CRTHU"			:	"Creating Service Unit",
    "WIZARD_HU_NOCOMMONDB"		:	"No Common Database existed.",
    
    "WIZARD_HU_OPT"				:	"* Optional Components",
    
    /** SBO-COMMON Creation **/
    "WIZARD_SBO_CRT"			:	"Common Database Creation",
    "WIZARD_SBO_WEL_TITLE"		:	"Welcome to the Common Database Creation.",
    "WIZARD_SBO_WEL_CONTENT"    :   "You can use this wizard to create an Common Database. Choose Next to continue.",
    "WIZARD_SBO_GUIDE_TITLE"    :   "Prerequisites",
    "WIZARD_SBO_GUIDE_DESCRIPTION": "Before you register a Common Database, make sure that all the following components are ready:",
    "WIZARD_NEWSBO_GUIDE_TITLE" :   "Prerequisites",
    "WIZARD_NEWSBO_GUIDE_DESCRIPTION": "Before you create a Common Database, make sure that all the following components are ready:",
    "WIZARD_SBO_CRTSBOCOMMON"	:	"Common Database Creation",
    "WIZARD_SBO_REG"			:	"Common Database Registration",
    "WIZARD_SBO_CRTPROGRESS"	:	"Creation Progress",
    "WIZARD_SBO_MSSQLINST"		:	"Database Instance",
    "WIZARD_SBO_CRTING"			:	"Creating Common Database",

    /** B1i Registration **/
    "WIZARD_B1I_REG"					:	"Integration Component Registration",
    "WIZARD_B1I_WEL_TITLE"				:	"Welcome to the Integration Component Registration.",
    "WIZARD_B1I_WEL_CONTENT"			:	"You can use this wizard to register an SAP Business One Integration Component (B1i). Choose Next to continue.",
    "WIZARD_B1I_BASICSETTINGS"			:	"Basic Settings",
    "WIZARD_B1I_BASICSETTINGS_CONTENT"	:	"Specify basic settings for the integration service.",
    "WIZARD_B1I_CONF"					:	"Configuration",
    "WIZARD_B1I_CONF_CONTENT"			:	"Configure the integration service.",
    "WIZARD_B1I_URL"					:	"Path",
    "WIZARD_B1I_CREATING"				:	"Creating Integration Component",

    /** Shared Folder Registration **/
    "WIZARD_SHRFOLDER_REG"          : "Shared Folder Registration",
    "WIZARD_SHRFOLDER_WEL_TITLE"    : "Welcome to the Shared Folder Registration.",
    "WIZARD_SHRFOLDER_WEL_CONTENT"	: "You can use this wizard to create a Shared Folder. Choose Next to continue.",
    "WIZARD_SHRFOLDER_REG_TITLE"	: "Register Shared Folder",
    "WIZARD_SHRFOLDER_CREATING"		: "Creating Shared Folder",

    /** Mailer Registration **/
    "WIZARD_MAILER_REG"				:	"Mailer Service Registration",
    "WIZARD_MAILER_WEL_TITLE"		:	"Welcome to the Mailer Service Registration.",
    "WIZARD_MAILER_WEL_CONTENT"		:	"You can use this wizard to register an SAP Business One Mailer Service. Choose Next to continue.",
    "WIZARD_MAILER_SETTINGTITLE"	:	"Specify basic settings for the mailer service.",
    "WIZARD_MAILER_REGISTERING"		:	"Registering Mailer Service",
    
    /** Presentation Server Registration **/
    "WIZARD_PRESVR_REG"             : "Presentation Server Registration",
    "WIZARD_PRESVR_WEL_TITLE"       : "Welcome to the Presentation Server Registration.",
    "WIZARD_PRESVR_WEL_CONTENT"     : "You can use this wizard to register a Presentation Server for hosting SAP Business One. Choose Next to continue.",
    "WIZARD_PRESVR_SETTINGTITLE"    : "Specify basic settings for the presentation server.",

    /** Software Repository Registration **/
    "WIZARD_SWREPO_REG"			:	"Software Repository Registration",
    "WIZADR_SWREPO_WEL_TITLE"	:	"Welcome to the Software Repository Registration.",
    "WIZADR_SWREPO_WEL_CONTENT"	:	"You can use this wizard to register an software Repository. Choose Next to continue.",
    "WIZADR_SWREPO_ROOTPATH"    :   "Upgrade Package Path",

    /** Software Repository Import Extension **/
    "WIZARD_SWREPO_EXTENSION_TITLE"              : "Extension Repository Registeration Wizard",
    "WIZARD_SWREPO_EXTENSION_WEL_TITLE"          : "Welcome to the wizard for SAP Business One Cloud-Import Extension.",
    "WIZARD_SWREPO_EXTENSION_WEL_CONTENT"        : "Here you will Import Extension(s). To continue,click next.",
    "WIZARD_SWREPO_EXTENSION_UPLOAD_CONFIG"      : "Upload configuration files",
    "WIZARD_SWREPO_EXTENSION_IMPORT_FINISH"      : "Import/finish",
    "WIZARD_SWREPO_EXTENSION_UPLOAD_CONFIGFILE"  : "Upload the configuration files of Extensions",
    "WIZARD_SWREPO_EXTENSION_ARD_FILE"           : "Extension .ard file",
    "WIZARD_SWREPO_EXTENSION_PKG_FILE"           : "Setup Package file",
    "WIZARD_SWREPO_EXTENSION_INSTALL_PARAM_FILE" : "Installation parameter file",
    "WIZARD_SWREPO_EXTENSION_IMPORT_SUCCSESS" : "The following extensions are imported successfullly:",
    "WIZARD_SWREPO_EXTENSION_IMPORT_FAILED" : "The following extensions are imported with errors:",
    "WIZARD_SWREPO_EXTENSION_UPLOAD_STATUS" : "Upload Status",
    "WIZARD_SWREPO_EXTENSION_UPLOAD_Failure" : "Error Description",

    /** Company DB Creation **/
    "WIZARD_CPYDB_CRT"				:	"Company Database Creation Wizard",
    "WIZARD_CPYDB_WEL_TITLE"		:	"Welcome to the Company Database Creation Wizard.",
    "WIZARD_CPYDB_WEL_CONTENT"		:	"You can use this wizard to create an SAP Business One Company Database. Choose Next to continue.",
    "WIZARD_CPYDB_INFO"				:	"Company Information",
    "WIZARD_CPYDB_SUBTITLE"			:	"Specify the company information.",
    "WIZARD_CPYDB_POSTINGPERIOD"	:	"Posting Periods",
    "WIZARD_CPYDB_POSTINGSUBTITLE"	:	"Specify the settings for posting periods.",
    "WIZARD_CPYDB_PACKAGEINFO"      :   "Select Package",
    "WIZARD_CPYDB_PACKAGESUBTITLE"  :   "Select a solution package for creating a new company.", 
    "WIZARD_CPYDB_PCODE"			:	"Period Code",
    "WIZARD_CPYDB_PNAME"			:	"Period Name",
    "WIZARD_CPYDB_PSUBTYPE"			:	"Period Sub Type",
    "WIZARD_CPYDB_PSUBNAME"			:	"Number of Periods",
    "WIZARD_CPYDB_PDATE"			:	"Period Posting Date",
    "WIZARD_CPYDB_CREATING"			:	"Creating Company Database",
    "WIZARD_CPYDB_NEW4NORMAL"       :   "New", 
    "WIZARD_CPYDB_NEW4NORMAL_DES"   :   "Creates a default company database.", 
    "WIZARD_CPYDB_NEW4PACKAGE"      :   "New from package",
    "WIZARD_CPYDB_NEW4PACKAGE_DES": "Creates a new company database using a solution package (.PAK).",
    "WIZARD_CRTDB_PKG_STEP4_USERDEFINED": "After you create the company database, manually configure the chart of accounts in the SAP Business One application.",
    "WIZARD_CRTDB_PKG_STEP4_PREDEFINED": "Creates a common chart of accounts structure based on the specified localization.",

    /** Operator **/
    "OPERATOR_ADD": "Add Operator",
    "USER_ADD": "Add User",
    "OPERATOR_EDIT": "Edit Operator",
    "PROMPT": "Only Cloud Operators can have superuser privileges.",
	
	/** Register Tenant **/
	"WIZARD_REGISTER_TENANT_TITLE": "Tenant Registration Wizard",
	"WIZARD_REGISTER_TENANT_WELCOME_TITLE": "Welcome to the Tenant Registration Wizard.",
	"WIZARD_REGISTER_TENANT_WELCOME_SUBTITLE": "You can use this wizard to register a new tenant for an existing service unit and an existing company database. Choose Next to continue.",

    /** New Tenant **/
    "WIZARD_TENANT_TITLE"			: "Tenant Creation Wizard",
    "WIZARD_TENANT_WELCOME_TITLE"	: "Welcome to the Tenant Creation Wizard.",
    "WIZARD_TENANT_WELCOME_SUBTITLE": "You can use this wizard to create a new tenant for an existing Service Unit. Choose Next to continue.",
    "WIZARD_TENANT_GUIDE_TITLE": "Prerequisites",
    "WIZARD_TENANT_GUIDE_DESCRIPTION": "Before you create a new tenant, make sure that all the following components are ready:",
    "TENANT_CHOOSE_HU_TITLE"		: "Select Service Unit",
    "TENANT_CHOOSE_HU_SUBTITLE"		: "Select the Service Unit in which you want to create a tenant.",
    "TENANT_PROFILE_TITLE"			: "Customer Profile",
    "TENANT_PROFILE_SUBTITLE"		: "Enter the customer's information.",
    "TENANT_LICENSE_IMPORT_TITLE"	: "License Import",
    "TENANT_LICENSE_IMPORT_SUBTITLE": "Select an existing license file or import a new license file.",
    "TENANT_COMPANYDB_TITLE"		: "Company Database",
    "TENANT_LICENSE_ASSIGN_TITLE"	: "Add Users and Assign Licenses",
    "TENANT_LICENSE_ASSIGN_STEP"	: "Add Users & Assign Licenses",
    "TENANT_LICENSE_ASSIGN_SUBTITLE": "Add one or more SAP Business One Users and assign licenses.",
    "TENANT_SHARED_FOLDER_TITLE"	: "Business One Shared Folder",
    "TENANT_SHARED_FOLDER_SUBTITLE"	: "Select a Business One Shared Folder.",
    "TENANT_COUNT"					: "No. of Tenants",
    "TENANT_NEW_HU"					: "New Service Unit",
    "TENANT_LICENSE_FILE"			: "License file",
    
    "WIZARD_TENANT_CREATING"		: "Creating Tenant",
    "WIZARD_TENANT_HULIST"			: "Service Unit List",
    "WIZARD_TENANT_LIVMDL"			: "License Modules",
    "WIZARD_TENANT_AVINUM"			: "Available Number",
    "WIZARD_TENANT_SELECTSHR"		: "Business One Shared Folder",
    "WIZARD_TENANT_CRTCPYDB"		: "Creating Company",
    "WIZARD_TENANT_CRTUSER"			: "Creating User",
    "WIZARD_TENANT_ASSIGNUSER"		: "Assigning Permission",
    
    "WIZARD_TENANT_UNQCMP"			: "Only one productive company could exist in a tenant.",
    "WIZARD_TENANT_UNQNAME"			: "Company name can not be duplicated in a tenant.",
    
    
    /******MS SQL*******/
    "WIZARD_DBINST_TITLE"			: "Database Instance Registration",
    "WIZARD_DBINST_REG"				: "Registering Database Instance",
    
    /****************** Add User ******************/
    "WIZARD_USER_ENTERUSERNAME"		: "Enter a domain user name",
    "WIZARD_USER_ALREADYEXISTS"		: "User name exists in domain",
    "WIZARD_USER_ISSUPERUSER"		: "Superuser",
    
    
    /*************************************************Wizard*****************************************************/
    
    //Component - dataform
    "DATAFORM_EDIT"		: "Edit",
    "DATAFORM_SAVE"		: "Save",
    "DATAFORM_CANCEL"	: "Cancel",
    "DATAFORM_IMPORT"	: "Import",
    //Hosting Unit
    "BUTTON_HU_NEW": "New",
    "BUTTON_HU_VIEW": "View All",
    "BUTTON_HU_UPGRADE":"Upgrade",
    "BUTTON_HU_PREUPGRADE": "Pre-upgrade Testing",
    "BUTTON_HU_CONFIG": "Configure",
    "BUTTON_HU_DELETE":"Delete",
    "HU_GD_NAME": "Service Unit Name",
    "HU_GD_TENANTCOUNT": "Number of Tenants",
    //Tenant
    "BUTTON_TENANT_NEW": "New",
    "BUTTON_TENANT_VIEW": "View All",
    //Infrastructure Overview
    "BUTTON_DBINSTANCE_NEW": "Register",
    "BUTTON_DBINSTANCE_VIEW": "View All",
    
    //status
    "STATUS_ONLINE"		: "Online",
    "STATUS_OFFLINE"	: "Offline",
    "STATUS_MAINTENANCE": "Maintenance",
    "STATUS_EXIST": "Exsit",
    "STATUS_NOTEXIST": "Not exist",
    "STATUS_ACTIVE": "Active",
    "STATUS_INACTIVE": "Inactive",
    "TXT_EXIST": "exist",
     
    //purpose
    "HU_PRODUCTIVE"     	:	"Productive",
    "HU_TESTING"         	:	"Testing",
    "HU_DEMO"       		:	"Demo",
    "HU_ROLLINGUPGRADE"		:	"Upgrade",
        
    "VALIDITY_VALUEMISSSING": "This field is required",
    "VALIDITY_PATTERNMISMATCH": "Format is invaid",
    "VALIDITY_NAMEDUPLICATED": "The name is duplicated",

    //Extension/Add-On
    "ADDON_ALL":           "Add-Ons",
    "ADDON_USER_PREFERENCE":           "User Preference",

    //////////////Application Management Overview//////////////

    "INFMGR_OVERVIEW_WELCOME": "Infrastructure Management Center",
    "APPMGR_OVERVIEW_WELCOME": "Welcome to Presentation Management Center",
    "INFMGR_INTRODUCE": "",
    "APPMGR_INTRODUCE": "",
    "APP": "Application",
    "HU_INF": "Required Components",
    "HU_INF_DESCRIPTION": "Before you create a Service Unit, make sure that all the following components are ready:",
    "TENANT_INF": "Required Components",
    "TENANT_INF_DESCRIPTION": "Before you create a Tenant, make sure that all the following components are ready:",
    "OPTIONAL": "Optional",
    "SHARED_COMPONENTS": "1. Components shared between multiple Service Units:",
    "MONOPOLIZED_COMPONENT": "2. Components dedicated to a single Service Unit:",

    "RES_SHARED_FOLDER_B1": "SharedFolder B1",
    "RES_SHARED_FOLDER_BACKUP": "SharedFolder Backup",
    "OPERATOR": "Cloud Operator",

    "DBINSTANCE_INTRODUCE":"Includes all company databases and common databases.",
    "PRESENTATION_SERVER_INTRODUCE": "Provides remote access to the SAP Business One client application.",
    "LIC_SERVER_INTRODUCE":"Maintains user sessions and purchased licenses.",
    "B1I_SERVER_INTRODUCE": "Enables the use of dashboards, mobile devices, and third-party integration with SAP Business One.",
    "SBO_COMMON_INTRODUCE": "Stores system data, update packages, and add-ons.",
    "MAILER_SERVICE_INTRODUCE":"Enables users to send emails and faxes from SAP Business One.",
    "SOFTWAREREPO_INTRODUCE": "Contains SAP Business One installation packages, upgrade packages, and add-ons.",
    "RES_B1_FOLDER_INTRODUCE": "Stores attachments, images, and document templates for a single tenant.",
    "RES_SHARED_TYPE_DBBACK_INTRODUCE": "Contains database backup files.",
    "HOSTUNIT_INTRODUCE":"A collection of the software components, servers, and storage required to provide a full SAP Business One installation.<br/> All SAP Business One components in a single service unit have the same version and add-ons. ",
    "TENANT_INTRODUCE": "A tenant is a client organization that has purchased a subscription to remotely access SAP Business One for a pre-defined period of time, according to contractual conditions. Multiple tenants may share a single service unit, with tenants data and configuration partitioned across multiple company databases and file repositories.",
    "OPERATOR_INTRODUCE": "An authorized Cloud Control Center user responsible for managing an SAP Business One On Demand landscape.",

    "OVERVIEW_SW": "Service Components - Sharable between Service Units",
    "OVERVIEW_B1CENTRAL": "Service Components - Dedicate to one Service Unit",
    
	"COLUMN_MOUNTPOINT": "Mount Point",
    "COLUMN_ACCESSURL": "Access URL"
}

